architecture: v0.1.5
callback_patience: 20
codes:
- Adaptation
- Monitoring
- Off-topic
- Strategy enactment
- Task definition
dataset_name: macro_level
embedding_model: https://tfhub.dev/google/universal-sentence-encoder-multilingual/3
epochs: 1000
l1_reg: 0.01
l2_reg: 0.01
learning_rate: 0.0005
min_words: 1
sent_dropout: 0.1
sent_hl_units: 16
stop_words_file: null
task: train
validation_split: 0.1
wandb_project: macro_level_classifier
