_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": epoch/val_f1_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/f1_score
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.17
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 7
                - 16
                - 23
                - 38
                - 55
            "4": 3.10.17
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
architecture:
    value: v0.1.5
callback_patience:
    value: 20
codes:
    value:
        - Adaptation
        - Monitoring
        - Off-topic
        - Strategy enactment
        - Task definition
dataset_name:
    value: macro_level
embedding_model:
    value: https://tfhub.dev/google/universal-sentence-encoder-multilingual/3
epochs:
    value: 1000
l1_reg:
    value: 0.01
l2_reg:
    value: 0.01
learning_rate:
    value: 0.0005
min_words:
    value: 1
sent_dropout:
    value: 0.4
sent_hl_units:
    value: 256
stop_words_file:
    value: null
task:
    value: undefined
validation_split:
    value: 0.1
wandb_project:
    value: macro_level_classifier
